Repository php-vcr/php-vcr, pull requests merged in 2022-12, with the labels that each got.

#376 360 php 81 compatibility
  .github/workflows/tests.yml
  composer.json
  docker-compose.yaml
  resources/docker/workspace/8.0/Dockerfile
  resources/docker/workspace/8.1/Dockerfile
  src/VCR/CodeTransform/AbstractCodeTransform.php
  src/VCR/Storage/AbstractStorage.php
  src/VCR/Storage/Blackhole.php
  src/VCR/Storage/Yaml.php
  tests/Unit/Storage/AbstractStorageTest.php
  tests/Unit/Storage/BlackholeTest.php
Labels: Bug

#378 Refactor dev ci
  .ecrc
  .editorconfig
  .gitattributes
  .github/workflows/continuous integration.yml
  LICENSE.md
  composer.json
  phpstan.neon
  src/VCR/Util/HttpUtil.php
  tests/Unit/CodeTransform/SoapCodeTransformTest.php
  tests/Unit/RequestTest.php
Labels: CI

#379 Record identical requests
  phpstan-baseline.neon
  src/VCR/Cassette.php
  src/VCR/Request.php
  src/VCR/Storage/Storage.php
  src/VCR/Videorecorder.php
  tests/Unit/CassetteTest.php
  tests/Unit/VideorecorderTest.php
Labels: Feature

#380 [1.5] Record identical requests
  phpstan-baseline.neon
  src/VCR/Cassette.php
  src/VCR/Request.php
  src/VCR/Storage/Storage.php
  src/VCR/Videorecorder.php
  tests/Unit/CassetteTest.php
  tests/Unit/VideorecorderTest.php
  tests/fixtures/unittest_curl_test
  tests/fixtures/unittest_streamwrapper_test
Labels: Feature

#365 #336 Proper Detection of EventDispatcherInterface [1.5]
  src/VCR/Videorecorder.php
Labels: Bug

#361 Support for Symfony 6
  composer.json
Labels: Feature

#382 FIX: Read the whole stream and perform code transformations
  src/VCR/CodeTransform/AbstractCodeTransform.php
Labels: Bug

#384 FIX: Read the whole stream and perform code transformations
  src/VCR/CodeTransform/AbstractCodeTransform.php
Labels: Bug, Backport
