Repository php-vcr/php-vcr, pull requests merged in 2023-02, with the labels that each got.

#381 Add CURLINFO_APPCONNECT_TIME to CurlHelper
  src/VCR/Util/CurlHelper.php
  tests/Unit/LibraryHooks/CurlHookTest.php
Labels: Bug, Status: Needs review

#386 TASK: Update README.md
  README.md
Labels: Documentation

#387 TASK: Drop support for php 8.2
  composer.json
Labels: Bug
