Repository php-vcr/php-vcr, pull requests merged in 2024-02, with the labels that each got.

#407 Fix pipeline (phpstan & phpcsfixer)
  phpstan-baseline.neon
  src/VCR/Configuration.php
  src/VCR/LibraryHooks/CurlHook.php
  src/VCR/Response.php
  src/VCR/Storage/Yaml.php
  src/VCR/Util/Assertion.php
  src/VCR/Util/CurlHelper.php
  src/VCR/Util/StreamHelper.php
  src/VCR/Util/StreamProcessor.php
  src/VCR/VCRFactory.php
  src/VCR/Videorecorder.php
  tests/Unit/ConfigurationTest.php
  tests/Unit/Util/StreamProcessorTest.php
  tests/bootstrap.php
Labels: Bug, CI

#408 FEATURE: Added php 8.3 workspace docker image
  docker-compose.yaml
  resources/docker/workspace/8.3/Dockerfile
Labels: CI

#409 Allow Symfony 7
  composer.json
Labels: Feature, Dependencies
